name: coclico
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pygeos
  - pyogrio
  - xarray
  - netcdf4
  - numpy
  - pandas
  - matplotlib
  - folium
  - mapclassify
  - pyarrow
  - rasterio
  - rioxarray
  - jupyterlab
  - bandit
  - jupyterlab_code_formatter
  - isort
  - black
  - zarr
  - h5py
  - nb_black
  - fiona
  - geojson
  - gcsfs
  - pystac
  - python-dotenv
  - datacube
  - google-cloud-storage
  - pip3:
      - xstac
      - mapbox
      - mapboxcli # requires monkey patch for python 3.10
